<?php
/**
 * @var Webinse_Faq_Block_Faq
 */
?>
<?php $helper = Mage::helper('lessons4'); ?>
<?php $item   = $this->getFaqById(); ?>
<?php $k = 1; ?>
<form action="<?php echo Mage::getUrl('lessons4/index/save'); ?>" method="post" id="form-validate">
<input type="hidden" name="id" value="<?php echo $item->getId(); ?>">
    <h2 class="legend"><?php if ($item->getId()): ?><?php echo $helper->__('Edit') ?><?php else: ?><?php echo $helper->__('Add') ?><?php endif; ?></h2>
    <ul class="form-list">
        <li class="wide">
            <label class="required"><em>*</em><?php echo $helper->__('Question') ?></label>
            <div class="input-box">
                <input type="text" name="question" form="form-validate" value="<?php echo $item->getQuestion(); ?>" title="<?php echo $helper->__('question') ?>" class="input-text required-entry" />
            </div>

        </li>

	<li class="wide">
            <label class="required"><em>*</em><?php echo $helper->__('Answer') ?></label>
            <div class="input-box">
                <input type="text" name="answer" form="form-validate" value="<?php echo $item->getAnswer(); ?>" title="<?php echo $helper->__('answer') ?>" class="input-text required-entry" aria-describedby="basic-addon1"/>
            </div>
        </li>
    </ul>
	<div>
	<button type="submit" form="form-validate"><?php if ($item->getId()): ?><?php echo $helper->__('Edit') ?><?php else: ?><?php echo $helper->__('Add') ?><?php endif; ?></button>
	</div>
<input type="hidden" name="user_id" value="<?php echo $k; ?>">
</form>

<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
//]]>
</script>


